language: python
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  global:
  - CC=gcc-4.8
  - CXX=g++-4.8
matrix:
  include:
    - python: 3.6
      env: TENSORFLOW_VERSION=1.8
    - python: 3.6
      env: TENSORFLOW_VERSION=1.12
    - python: 3.6
      env: TENSORFLOW_VERSION=1.14
    - python: 3.7
      env: TENSORFLOW_VERSION=1.14
before_install:
  - pip install --upgrade pip
  - pip install tensorflow==$TENSORFLOW_VERSION
install:
  - pip install -vvv .[test]
script:
  - cd source/tests && python -m unittest
