on:
  push:
    branches-ignore:
      - "gh-readonly-queue/**"
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
name: Test Python
jobs:
  testpython:
    name: Test Python
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - python: 3.8
            tf:
            torch:
          - python: "3.11"
            tf:
            torch:

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - uses: mpi4py/setup-mpi@v1
      with:
        mpi: openmpi
    - uses: hendrikmuhs/ccache-action@ff9f6cc67d49b9acaa9e102f80d1ea8a0c86a6dd
      with:
        key: ${{ github.job }}-${{ matrix.python }}-${{ matrix.tf }}-${{ matrix.torch }}
    - run: python -m pip install -U uv
    - run: uv pip install --system -e .[cpu,test,torch]
      env:
        # Please note that uv has some issues with finding
        # existing TensorFlow package. Currently, it uses
        # TensorFlow in the build dependency, but if it
        # changes, setting `TENSORFLOW_ROOT`.
        TENSORFLOW_VERSION: ${{ matrix.tf }}
        DP_BUILD_TESTING: 1
        CMAKE_C_COMPILER_LAUNCHER: ccache
        CMAKE_CXX_COMPILER_LAUNCHER: ccache
        CCACHE_COMPILERCHECK: content
    - run: uv pip install --system --no-build-isolation horovod mpi4py
      env:
        HOROVOD_WITH_TENSORFLOW: 1
        HOROVOD_WITHOUT_PYTORCH: 1
        HOROVOD_WITHOUT_GLOO: 1
    - run: dp --version
    - run: pytest --cov=deepmd source/tests --durations=0
      env:
        NUM_WORKERS: 0
    - uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  pass:
    name: Pass testing Python
    needs: [testpython]
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
